CaelumEstoque/Models/CategoriaDoProduto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class CategoriaDoProduto
    {
        public int Id { get; set; }

        public String Nome { get; set; }

        public String Descricao { get; set; }
    }
}

CaelumEstoque/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Produto
    {
        public int Id { get; set; }

        [Required, StringLength(20)]
        public String Nome { get; set; }

        [Range(0.1, 10000.1, ErrorMessage = "Preço do produto deve estar entre 0,00 e 10.000,00")]
        public float Preco { get; set; }

        public CategoriaDoProduto Categoria { get; set; }

        public int? CategoriaId { get; set; }

        [Required, StringLength(100, ErrorMessage = "")]
        public String Descricao { get; set; }
        
        [Range(1, Int32.MaxValue, ErrorMessage = "O campo Quantidade deve ser maior que zero.")]
        public int Quantidade { get; set; }
    }
}

CaelumEstoque/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Senha { get; set; }
    }
}

CaelumEstoque/Controllers/CategoriaController.cs
using CaelumEstoque.DAO;
using CaelumEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class CategoriaController : Controller
    {
        public ActionResult Index()
        {
            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Form ()
        {
            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            return View();
        }

        [HttpPost]
        public ActionResult Adiciona (CategoriaDoProduto categoria)
        {
            CategoriasDAO dao = new CategoriasDAO();
            dao.Adiciona(categoria);
            return RedirectToAction("index");
        }
    }
}

CaelumEstoque/Controllers/ContadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class ContadorController : Controller
    {
        // GET: Contador
        public ActionResult Index()
        {
            object valorNaSession = Session["contador"];
            int contador = Convert.ToInt32(valorNaSession);
            contador++;
            Session["contador"] = contador;
            return View(contador);
        }
    }
}

CaelumEstoque/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CaelumEstoque/Controllers/LoginController.cs
using CaelumEstoque.DAO;
using CaelumEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica (string login, string senha)
        {
            UsuariosDAO usuariosDAO = new UsuariosDAO();
            Usuario usuario = usuariosDAO.Busca(login, senha);
            if (usuario != null)
            {
                Session["usuarioLogado"] = usuario;
                return RedirectToAction("Index", "Produto");
            }
            else
            {
                return RedirectToAction("Index");
            }            
        }
    }
}

CaelumEstoque/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaelumEstoque.DAO;
using CaelumEstoque.Filtros;
using CaelumEstoque.Models;

namespace CaelumEstoque.Controllers
{
    [AutorizacaoFilter]
    public class ProdutoController : Controller
    {
        [Route("produtos", Name = "ListaProdutos")]        
        public ActionResult Index()
        {
            ProdutosDAO dao = new ProdutosDAO();
            IList<Produto> produtos = dao.Lista();

            //acessado pela View usando ViewBag.Produtos
            //ViewBag.Produtos = produtos; 
            //return View();

            //acessado pela View usando Model
            return View(produtos);
        }

        public ActionResult Form()
        {
            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            ViewBag.Produto = new Produto();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(Produto produto)
        {
            int idDaInformatcia = 1;
            if (produto.CategoriaId.Equals(idDaInformatcia) && produto.Preco < 100)
            {
                ModelState.AddModelError("produto.Invalido", "Informática com preço abaixo de 100 reais.");
            }
            if (ModelState.IsValid)
            {
                ProdutosDAO dao = new ProdutosDAO();
                dao.Adiciona(produto);
                //return RedirectToAction("index", "Produto");
                return RedirectToAction("index");
            }
            else
            {
                ViewBag.Produto = produto;
                CategoriasDAO categoriasDAO = new CategoriasDAO();
                ViewBag.Categorias = categoriasDAO.Lista();
                return View("Form");
            }
        }

        [Route("produtos/{id}", Name = "VisualizaProdutos")]
        public ActionResult Visualiza(int id)
        {
            ProdutosDAO produtosDAO = new ProdutosDAO();
            Produto produto = produtosDAO.BuscaPorId(id);
            ViewBag.Produto = produto;
            return View();
        }

        public ActionResult DecrementaQtd(int id)
        {
            ProdutosDAO produtosDAO = new ProdutosDAO();
            Produto produto = produtosDAO.BuscaPorId(id);
            produto.Quantidade--;
            produtosDAO.Atualiza(produto);
            return Json(produto);
        }
    }
}

CaelumEstoque/Views/Categoria/Form.cshtml
<form action="/Categoria/Adiciona" method="post">
    <label for="nome">Nome: </label>
    <input id="nome" name="categoria.Nome" />

    <label for="descricao">Descrição: </label>
    <input id="descricao" name="categoria.Descricao" />

    <input type="submit" value="Cadastrar" />
</form>

CaelumEstoque/Views/Categoria/Index.cshtml
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var categoria in ViewBag.Categorias)
        {
            <tr>
                <td>@categoria.Id</td>
                <td>@categoria.Nome</td>
                <td>@categoria.Descricao</td>
            </tr>
        }
    </tbody>
</table>

CaelumEstoque/Views/Contador/Index.cshtml
Contador : @Model

CaelumEstoque/Views/Home/Index.cshtml
<h1>Página Inicial da aplicação</h1>

CaelumEstoque/Views/Login/Index.cshtml
<form action="/Login/Autentica" method="post">
    <label for="login">Login:</label>
    <input type="text" name="login" id="login" class="form-control" />

    <label for="senha">Senha:</label>
    <input type="password" name="senha" id="senha" class="form-control" />

    <input type="submit" value="Autenticar"/>
</form>

CaelumEstoque/Views/Produto/Adiciona.cshtml
<h1>Produto adcionado com sucesso!</h1>

CaelumEstoque/Views/Produto/Form.cshtml
<form action="/Produto/Adiciona" method="post">

    @Html.AntiForgeryToken()

    <label for="nome">Nome: </label>
    <input id="nome" name="produto.Nome" value="@ViewBag.Produto.Nome" class="form-control"/>
    @Html.ValidationMessage("produto.Nome")

    <label for="preco">Preço: </label>
    <input id="preco" name="produto.Preco" value="@ViewBag.Produto.Preco" class="form-control"/>
    @Html.ValidationMessage("produto.Preco")

    <label for="quantidade">Quantidade: </label>
    <input id="quantidade" name="produto.Quantidade" value="@ViewBag.Produto.Quantidade" class="form-control"/>
    @Html.ValidationMessage("produto.Quantidade")

    <label for="descricao">Descrição: </label>
    <input id="descricao" name="produto.Descricao" value="@ViewBag.Produto.Descricao" class="form-control" />
    @Html.ValidationMessage("produto.Descricao")

    <label for="categoria">Categoria: </label>
    <select id="categoria" name="produto.CategoriaId" class="form-control">
        @foreach (var categoria in ViewBag.Categorias)
        {
            <option value="@categoria.Id" selected="@categoria.Id.Equals(ViewBag.Produto.CategoriaId)">@categoria.Nome</option>            
        }
    </select>

    <input type="submit" value="Cadastrar" class="form-control" />
</form>

CaelumEstoque/Views/Produto/Index.cshtml
@model IList<CaelumEstoque.Models.Produto>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in Model)
        {
            <tr>
                <td>@produto.Id</td>
                <td>
                    <!@Html.ActionLink(produto.Nome, "Visualiza", new { id = produto.Id})>
                    @Html.RouteLink(produto.Nome, "VisualizaProdutos", new { id = produto.Id })
                </td>
                <td id="quantidade@(produto.Id)">@produto.Quantidade</td>
                <td><a href="#" onclick="decrementa(@produto.Id)">Decrementar</a></td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">
    function decrementa(produtoId) {
        var url = "@Url.Action("DecrementaQtd", "Produto")";
        $.post(url, { id: produtoId }, atualiza);
    }

    function atualiza(resposta) {
        $("#quantidade" + resposta.Id).html(resposta.Quantidade);
    }
</script>

CaelumEstoque/Views/Produto/Visualiza.cshtml
Id: @ViewBag.Produto.Id <br />
Nome: @ViewBag.Produto.Nome <br />
Quantidade: @ViewBag.Produto.Quantidade <br />
Preço: @ViewBag.Produto.Preco <br />
Descrição: @ViewBag.Produto.Descricao <br />
Categoria: @ViewBag.Produto.Categoria.Nome <br />

@Html.RouteLink("Voltar para a lista", "ListaProdutos")

CaelumEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link rel="stylesheet" href="~/Content/Css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Css/Site.css" />
</head>
<body>
    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
            </ul>
            <h3 class="text-muted">Caelum Estoque</h3>
        </div>
        <div id="conteudo">
            @RenderBody()
        </div>
    </div>
</body>
</html>